### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by estiloinfo** [damencho/jitsi-meet#8]
HI, i actualize main-es.json and main-esUs.json, i attach the complete files and patch. I you want update de repo.

But main-es.json not change text "You ar the only in the meeting" and "Invite more people" I did not find how to fix it.

Regards

[patch.zip](https://github.com/damencho/jitsi-meet/files/4671914/patch.zip)
[lang.zip](https://github.com/damencho/jitsi-meet/files/4671901/lang.zip)

**Comment by damencho** [comment]
Wrong repo. Create PR in jitsi/jitsi-meet

**Comment by estiloinfo** [comment]
Thanks, Sorry!
